before:
  hooks:
    - go mod tidy
    - go mod .
builds:
  -
    id: commenter
    main: ./cmd/cli
    binary: horusec-commenter
    env:
      - CGO_ENABLED=0
      - GOFLAGS=-mod=vendor
    goos:
      - linux
    goarch:
      - amd64

snapshot:
  name_template: "{{ .Tag }}-next"

archives:
  -
    format: binary
    name_template: "{{ .Binary}}-{{ .Os }}-{{ .Arch }}"

release:
  prerelease: auto
  github:
    owner: upbanx
    name: horusec-action